"""
Graph State Schema for CRAG Workflow.

Defines the TypedDict that maintains state throughout the LangGraph execution.
"""

from typing import TypedDict, List, Literal, Optional, Any


class Message(TypedDict):
    """A single message in the conversation history."""
    role: Literal["user", "assistant"]
    content: str


class GraphState(TypedDict):
    """
    State maintained throughout the CRAG workflow.
    
    Attributes:
        question: The user's original query
        rewritten_query: The standalone search query (after rewriting with history context)
        history: Conversation history for multi-turn support
        documents: List of retrieved text chunks (from vectorstore or web)
        generation: The final answer generated by the LLM
        web_search: Flag indicating if web search is required ("yes"/"no")
        web_search_done: Whether web search has already been performed (prevents redundant calls)
        generation_attempts: Counter for generation retry loops
        generation_grade: Result of grading the generation ("useful", "not supported", "not useful")
        route_decision: The routing decision ("vectorstore" or "web_search")
    """
    question: str
    rewritten_query: Optional[str]
    history: List[Message]
    documents: List[Any]  # List of Document objects from retrieval.py
    generation: str
    web_search: Literal["yes", "no"]
    web_search_done: bool
    generation_attempts: int
    generation_grade: Optional[Literal["useful", "not supported", "not useful"]]
    route_decision: Optional[Literal["vectorstore", "web_search"]]
